### ISSUE TITLE
Nonpersistence of cached maps

### ISSUE THREAD

**Issue by ghost** [applikationsprogramvara/osmv#1]
I encountered a problem while using this application: The cached maps are ephimeral.

**Comment by mspnr** [comment]
Could you please provide some more information about your issue? 
Currently it is not clear how to reproduce your issue.

Please be aware, that there is no dedicated "offline"-function in the application. But the library generally allows reuse of the cached tiles. E.g. if you open some location in the "online"-mode in a certain zoom-level and scroll the map along some path, allowing it to download the tiles in full, these tiles will be available in the same zoom in the "offline"-mode. Although the neighbor areas and other zoom-levels may stay blank, so you need to be sure that you use the same zoom and the same location.

**Comment by ghost** [comment]
Sorry for misspelling of ephemeral. You know what that word means, don't you? The problem that I met is that the cached tiles are not persistent. E.g. after a few days they dissolve. I think it is because a limit of size in the cache database, like about 500 mb. Do you something about it?

**Comment by mspnr** [comment]
I would suggest you to check out the appropriate page of the source library for information about map tiles expiration period: [Offline Map Tiles](https://github.com/osmdroid/osmdroid/wiki/Offline-Map-Tiles#use-osmdroids-cache-manager-on-device---version-52)
